### ISSUE TITLE
Sitemap bug

### ISSUE THREAD

**Issue by trf000** [AppStateESS/phpwebsite#119]
Might only pertain to me as my permissions are so screwed up, but in the 1.7 release of phpws, if you create a sitemap with the sitemap mod and your destination does not have write permissions, the mod will still say sitemap created. You can still download it, but it won't write it to the server.

Probably won't affect anyone, but I think there should be some server permission checking like in File Cabinet over whether the dir is writeable.

**Comment by Stardog** [comment]
Deprecated module. Sorry.
