### ISSUE TITLE
modal for qr mod

### ISSUE THREAD

**Issue by trf000** [AppStateESS/phpwebsite#200]
not sure if this should happen or not. I'd also ad a download button. some people actually do not know you can right-click and save image.

**Comment by Stardog** [comment]
In this one case, I am not sure about a modal. It is easier to print the qr out if it is alone in its own window.

**Comment by trf000** [comment]
We don't usually print them. right click and save as for use in printed
promotional materials.

On Mon, Feb 16, 2015 at 12:50 PM, Matthew McNaney <notifications@github.com>
wrote:

> In this one case, I am not sure about a modal. It is easier to print the
> qr out if it is alone in its own window.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppStateESS/phpwebsite/issues/200#issuecomment-74555154>
> .
>



-- 
Pretend inferiority and encourage his arrogance.

**Comment by Stardog** [comment]
I'll see what I can do.
