### ISSUE TITLE
Properties - update count limit

### ISSUE THREAD

**Issue by Stardog** [AppStateESS/phpwebsite#234]
Add code to prevent continual updates used to push a property to the top.

**Comment by trf000** [comment]
What? did you somehow get some free time? :)

On Wed, Apr 8, 2015 at 9:46 AM, Matthew McNaney <notifications@github.com>
wrote:

> Add code to prevent continual updates used to push a property to the top.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppStateESS/phpwebsite/issues/234>.
>



-- 
Pretend inferiority and encourage his arrogance.

**Comment by Stardog** [comment]
Moved here:
https://github.com/AppStateESS/properties/issues/5
