### ISSUE TITLE
upgrading core to 2.8.0 from 2.6.0

### ISSUE THREAD

**Issue by trf000** [AppStateESS/phpwebsite#237]
getting the following:

 Server Error

500 Internal Server Error

For URL /index.php method GET
Stack Depth 	Line 	File 	Function 	Class
0 	61 	/var/www/html/acweb/Global/PhpwebsiteController.php 	__construct 	Http\ErrorResponse
1 	40 	/var/www/html/acweb/index.php 	execute 	PhpwebsiteController

This error was originally caused by an uncaught exception "Unknown data type "longtext"" with code 0 in file /var/www/html/acweb/Global/Database/Datatype.php on line 78.
Stack Depth 	Line 	File 	Function 	Class
0 	163 	/var/www/html/acweb/Global/Database/Engine/mysql/Table.php 	factory 	Database\Datatype
1 	504 	/var/www/html/acweb/core/boost/update.php 	getDataType 	Database\Engine\mysql\Table
2 	245 	/var/www/html/acweb/mod/boost/class/Boost.php 	core_update 	N/A
3 	417 	/var/www/html/acweb/mod/boost/class/Boost.php 	onUpdate 	PHPWS_Boost
4 	978 	/var/www/html/acweb/mod/boost/class/Boost.php 	update 	PHPWS_Boost
5 	152 	/var/www/html/acweb/mod/boost/class/Action.php 	updateBranches 	PHPWS_Boost
6 	91 	/var/www/html/acweb/mod/boost/index.php 	updateModule 	Boost_Action
7 	54 	/var/www/html/acweb/Global/CompatibilityModule.php 	include 	N/A
8 	51 	/var/www/html/acweb/Global/PhpwebsiteController.php 	execute 	CompatibilityModule
9 	40 	/var/www/html/acweb/index.php 	execute 	PhpwebsiteController

**Comment by Stardog** [comment]
Odd. I don't get that error and it makes a text column, not a longtext column.
What is looks like is that getDataType is pulling your column which was already set to longtext maybe? In other words, you fixed it yourself prior to the update.
Let me know if this is the case. I will try and make a longtext datatype to prevent this in the meantime.

**Comment by trf000** [comment]
I may have. I'll double check. How's things?
