### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by trf000** [AppStateESS/phpwebsite#239]
Fresh install, clean database. Cannot create schedule with any theme. Thought it might just be mine, but the default bootstrap theme is the same.

**Comment by trf000** [comment]
Also the edit schedule button is not working either. I manually created a schedule to see if it was working as I noticed my production version of phpws it wasn't working there.

**Comment by Stardog** [comment]
This has to do with the inclusion of the bootstrap.js file and jquery.js. Take a look at https://github.com/AppStateESS/phpwebsite/commit/9bb7e379832aa078be164e453d7d7f898944fbbd
The javascript tag is moved to the top of theme.tpl. Doing this allowed the modal to work, but broke the dropdowns. phpws.js was added to initialize the dropdowns as well.

**Comment by Stardog** [comment]
Fixed with Bootstrap theme update.
