### ISSUE TITLE
Facebook Likebox

### ISSUE THREAD

**Issue by trf000** [AppStateESS/phpwebsite#240]
https://developers.facebook.com/docs/plugins/page-plugin

just an FYI... it is being depracated and replaced with a new page plugin tool.

**Comment by jlbooker** [comment]
Thanks for the heads up. The deprecation notice is at: https://developers.facebook.com/docs/plugins/like-box-for-pages

According to that, the Like Box implementation will automatically fall back to the Page Plugin (or has already) on June 23rd, 2015. So, I'm not sure anything is going to break, but we should update our code soon.

**Comment by Stardog** [comment]
Updated by Chris Detsch.
https://github.com/AppStateESS/phpwebsite/commit/9d4aac3876d3158634e280bfbb61d973ccc26803
