### ISSUE TITLE
modal issue with popovers

### ISSUE THREAD

**Issue by trf000** [AppStateESS/phpwebsite#255]
If you have a form in a modal (Pagesmith edit, calendar) and one of the CKEditor buttons uses a popover, text fields cannot get focus, not even with tabs.

**Comment by trf000** [comment]
Just sent you a pull request. I think I fixed this.

**Comment by Stardog** [comment]
What is the status of this?

**Comment by trf000** [comment]
I tried to do a pull request, but somehow screwed that up :)
in pagesmith>javascript>script.js change line 69 to this

`$(document).on('shown.bs.modal', function(e) {`

**Comment by Stardog** [comment]
Made the change. Please check it out.
