### ISSUE TITLE
Calendar Date off by one day

### ISSUE THREAD

**Issue by trf000** [AppStateESS/phpwebsite#262]
If you try to add an event on a specific date, the event module populates the previous day. So if you selected June 17 and add an event, the modal shows June 16.

**Comment by Stardog** [comment]
It sounds like your timezone is off. Look at PHPWS_Time::getUserTZ. It looks at the user's cookie. If that isn't set, it get the timezone from the server using SERVER_TIME_ZONE (which is in defines.php).

Be aware that config files have changed.

phpwebsite/src/phpws/config/ has the server-wide settings

If your branch has a config/phpws/ directory with the same config file, it will use that instead.

Matt

**Comment by trf000** [comment]
Yep, that was it. Thanks!
